# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laura Cristiana Dragoi
email: laura.dragoi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Laura Cristiana Dragoi's website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lauradragoi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lauradragoi
github_username:  lauradragoi
repository: lauradragoi/lauracd

author:
  name: "Laura C.D."
  avatar: "/assets/images/bio-photo.jpg"
  bio: "💯"
  location: "Zürich, Switzerland"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-link"
      url: "mailto:laura.dragoi@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lauradragoi"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/laurazrh"

include:
  - "_pages"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
#
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-176090171-1"
    anonymize_ip: false # default
